version: "3.0"
services:
  db_Justransform:
    image: oagi1docker/srt-repo:Justransform_08212017
    ports:
      - 1521:1521
    volumes:
      - db-data:/u01/app/oracle

  web_Justransform:
    image: oagi1docker/srt-web:Justransform_08212017
    ports:
      - 8080:8080
    links:
      - db_Justransform:srt-repo
    depends_on:
      - db_Justransform

volumes:
  db-data:
